name: Build Image and Push to GHCR
on:
  workflow_call:
    inputs:
      build-target:
        required: false
        type: string
      # docker-arch:
      #   required: true
      #   type: string
      docker-build-args:
        required: false
        type: string
      pre-build-script:
        required: false
        type: string
      dockerfile-path:
        required: false
        type: string
        default: "./Dockerfile"
      custom-image-name:
        required: false
        type: string
      custom-image-tag:
        required: false
        type: string
      custom-image-tag-alt:
        required: false
        type: string
    secrets:
      docker-build-secrets:
        required: false
      DOCKER_HUB_TOKEN:
        required: false
    outputs:
      docker-tag:
        description: Docker Tag Value
        value: ${{ jobs.build-image.outputs.docker-tag }}
      docker-repo:
        description: Docker Registry and Repo without Tag
        value: ${{ jobs.build-image.outputs.docker-repo }}

env:
  REGISTRY: ghcr.io
  DOCKER_HUB_USER: occasio

jobs:
  build-image:
    name: Build Image With Dockerfile Target '${{ inputs.build-target }}'
    runs-on: occasio-runner-fleet
    outputs:
      docker-tag: ${{ steps.meta.outputs.version }}
      docker-repo: ${{ steps.docker-repo.outputs.DOCKER_REPOSITORY }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Github Repo Var to lower
        run: echo "DOCKER_REPOSITORY=$( echo ${{ env.REGISTRY }}/${{ github.repository }} | awk '{print tolower($0)}' )" >> $GITHUB_ENV
      - name: Github Repo Var Output
        id: docker-repo
        run: echo "DOCKER_REPOSITORY=$( echo ${{ env.REGISTRY }}/${{ github.repository }} | awk '{print tolower($0)}' )" >> $GITHUB_OUTPUT
      - name: Github Repo Owner to Lower
        run: echo "REPO_OWNER=$( echo ${{ github.repository_owner }} | awk '{print tolower($0)}' )" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        run: docker context create builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builder
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: occasio-machine
          password: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.custom-image-name != '' && format('{0}/{1}/{2}', env.REGISTRY, github.repository_owner, inputs.custom-image-name)  || env.DOCKER_REPOSITORY }}
          tags: |
            type=raw,priority=9999,value=${{ inputs.custom-image-tag != '' && format('{0}{1}', inputs.custom-image-tag, inputs.build-target != '' && format('-{0}', inputs.build-target) || '') || '' }}
            type=raw,priority=9998,value=${{ inputs.custom-image-tag-alt != '' && format('{0}{1}', inputs.custom-image-tag-alt, inputs.build-target != '' && format('-{0}', inputs.build-target) || '') || '' }}
            type=schedule
            type=ref,event=branch,pattern={{major}},suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=ref,event=pr,suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{version}},suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=semver,pattern={{major}},suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=sha,pattern={{major}},suffix=${{ inputs.build-target != '' && format( '-{0}', inputs.build-target) || ''}}
            type=raw,value=${{ inputs.build-target }}
      - name: Tag Info
        run: |
          echo "generated tags image: ${{ steps.meta.outputs.tags }}"
          echo "custom-image-tag  ${{ inputs.custom-image-tag }}"
          echo "custom-image-tag-alt  ${{ inputs.custom-image-tag-alt }}"
      - name: Run Pre-Build User-defined script
        run: bash -c '${{ inputs.pre-build-script }}'
      - name: Git checkout, Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: ${{ inputs.docker-build-args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfile-path }}
          platforms: ${{ inputs.docker-arch }}
          pull: true
          no-cache: false
          secrets: ${{ secrets.docker-build-secrets }}
          cache-from: type=registry,ref=${{ inputs.custom-image-name != '' && format('{0}/{1}/{2}', env.REGISTRY, env.REPO_OWNER, inputs.custom-image-name) || env.DOCKER_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ inputs.custom-image-name != '' && format('{0}/{1}/{2}', env.REGISTRY, env.REPO_OWNER, inputs.custom-image-name)  || env.DOCKER_REPOSITORY }}:buildcache,mode=max
          target: ${{ inputs.build-target }}
  scan-image:
    name: Scan Docker Image for Critical Vulnerabilities
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: occasio-machine
          password: ${{ github.token }}
      - name: Checkout Repo for .grype.yaml
        uses: actions/checkout@v3
      - name: Github Repo Owner to Lower
        run: echo "REPO_OWNER=$( echo ${{ github.repository_owner }} | awk '{print tolower($0)}' )" >> $GITHUB_ENV
      - name: Security Scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.custom-image-name != '' && inputs.custom-image-tag != '' && format('{0}/{1}/{2}:{3}', env.REGISTRY, env.REPO_OWNER, inputs.custom-image-name, inputs.custom-image-tag) || format('{0}:{1}', needs.build-image.outputs.docker-repo, needs.build-image.outputs.docker-tag) }}
          fail-build: false
          severity-cutoff: critical
          output-format: table
          only-fixed: true
