name: GPT Search Unified Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment for release"
        type: string
        required: false
        default: "none"
      chart_tag:
        description: "Force chart version override?"
        type: string
        required: false
        default: ""
      chart_overwrite:
        description: "Force chart overwrite?"
        type: boolean
        required: false
        default: false
      branch:
        type: string
        description: "Branch to release"
        required: false
    secrets:
      GHA_BOT_REPO_TOKEN:
        required: false
      DOCKER_HUB_TOKEN:
        required: false
    outputs:
      app_image_tag:
        description: "The app image tag that was built"
        value: ${{ jobs.gpt-version.outputs.app-image-tag-version }}
      chart_image_tag:
        description: "The chart image tag that was built"
        value: ${{ jobs.gpt-version.outputs.chart-image-tag-version }}
  
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for release"
        type: choice
        required: false
        default: "none"
        options:
          - none
          - rc-next
          - staging
      chart_tag:
        description: "Force chart version override?"
        required: false
        type: string
        default: ""
      chart_overwrite:
        description: "Force chart overwrite?"
        required: false
        type: boolean
        default: false
      branch:
        type: string
        description: "Branch to release"
        required: false
  
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Get version information
  gpt-version:
    uses: ./.github/workflows/get-chart-version-info.yaml
    secrets: inherit
    with:
      chart-path: "./charts/gpt-search/Chart.yaml"
  
  agent-flows-version:
    uses: ./.github/workflows/get-chart-version-info.yaml
    secrets: inherit
    with:
      chart-path: "./charts/agent-flows/Chart.yaml"

  # Build Docker images (conditional on event type)
  build-gpt-image:
    needs: [gpt-version]
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      docker-repo: "ghcr.io/${{ github.repository_owner }}/gpt-search"
      docker-tag: "${{ needs.gpt-version.outputs.app-image-tag-version }}"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: "ghcr.io/${{ github.repository_owner }}/gpt-search:${{ needs.gpt-version.outputs.app-image-tag-version }}"
          platforms: linux/amd64
  
  build-agent-flows-image:
    needs: agent-fows-version
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.agentflows
          push: false
          load: true
          tags: "ghcr.io/${{ github.repository_owner }}/agent-flows:${{ needs.agent-flows-version.outputs.app-image-tag-version }}"
          platforms: linux/amd64
      
  build-migrate-vector-image:
  needs: [gpt-version]
  if: github.event_name == 'pull_request' || github.event_name == 'push'
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        target: migration
        tags: "ghcr.io/${{ github.repository_owner }}/gpt-search:${{ needs.gpt-version.outputs.app-image-tag-version }}-migration"
        platforms: linux/amd64
      
  build-migrate-agent-image:
    needs: agent-fows-version
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.agentflows
          push: false
          load: true
          target: migration
          tags: "ghcr.io/${{ github.repository_owner }}/agent-flows:${{ needs.agent-flows-version.outputs.app-image-tag-version }}-migration"
          platforms: linux/amd64

  # Run tests
  docker-tests:
    name: Run Tests using Docker Image
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: occasio-runner-fleet
    needs: build-gpt-image
    timeout-minutes: 5
    env:
      DOCKER_REPO: ${{ needs.build-gpt-image.outputs.docker-repo }}
      DOCKER_TAG: ${{ needs.build-gpt-image.outputs.docker-tag }}
      DOCKER_TEST_IMAGE_TAG: gpt-search-test
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build Test Image
        run: >
          docker build
          --build-arg IMAGE=$DOCKER_REPO:$DOCKER_TAG
          -f Dockerfile.test
          -t $DOCKER_TEST_IMAGE_TAG .
      - name: Execute Pytest
        run: |
          set -o pipefail
          docker run -v /tmp:/tmp $DOCKER_TEST_IMAGE_TAG pytest \
            --cov-report=term-missing \
            --junitxml=/tmp/pytest.xml \
            --cov=gpt_search | tee /tmp/pytest-coverage.txt
      - name: Pytest coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /tmp/pytest-coverage.txt
          junitxml-path: /tmp/pytest.xml

  # Build and Release Helm Charts (conditional based on event type and input)
  helm-chart-release:
    needs: [gpt-version, agent-flows-version]
    if: >
      (github.event_name == 'workflow_dispatch' && inputs.environment != 'none') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/build-chart.yaml
    with:
      gpt_chart_tag: ${{ needs.gpt-version.outputs.chart-image-tag-version }}
      agent_flow_chart_tag: ${{ needs.agent-flows-version.outputs.chart-image-tag-version }}
      gpt_chart_overwrite: ${{ inputs.chart_overwrite == true || github.event_name == 'push' }}
      agent_flow_chart_overwrite: ${{ inputs.chart_overwrite == true || github.event_name == 'push' }}
    secrets: inherit